<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Claire Wang &amp; Xeno Hu">

<title>Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="final-project_files/libs/clipboard/clipboard.min.js"></script>
<script src="final-project_files/libs/quarto-html/quarto.js"></script>
<script src="final-project_files/libs/quarto-html/popper.min.js"></script>
<script src="final-project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final-project_files/libs/quarto-html/anchor.min.js"></script>
<link href="final-project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final-project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="final-project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final-project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final-project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Claire Wang &amp; Xeno Hu </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>Cardiovascular diseases (CVDs) are the leading cause of death in the United States, with one person dying of the disease every 34 seconds (Centers for Disease Control and Prevention, 2022). Previous research has highlighted male gender, old age, obesity, abnormal cholesterol and fasting blood glucose as important predictors for CVDs, among many others (Damen et al., 2016).</p>
<p>As CVD incidence continues to soar, the need for an effective predictive model cannot be overstated. Such a model could enable doctors to take preventive measures, treat patients early, or encourage individuals at high risk to adopt lifestyle changes. In this report, we aim to construct a predictive model based on the “Heart Failure Prediction Dataset” by assessing the 11 possible predictors (including chest pain type, resting blood pressure, cholesterol levels, maximum heart rate, resting ECG measurements, etc.). Our research question is, which combination of these factors is most effective in predicting CVDs? In answering this question, we seek to enhance the scientific community’s understanding of CVDs and their associated risk factors, ultimately contributing to better prevention, early identification, and management of this critical disease for both individuals and populations.</p>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">Data Description</h2>
<p>This “Heart Failure Prediction Dataset” includes 11 characteristics that can be utilized to anticipate the potential risk of a CVD; it is called “Heart Failure Prediction Dataset” because it is not uncommon for a CVD to lead to heart failure (Velagaleti et al., 2007). The dataset was formed by merging five heart-related datasets (the Cleveland, Hungarian, Switzerland, Long Beach VA, and Stalog Heart Datasets) based on their 11 common features.This dataset is currently the largest available heart disease dataset for research purposes, consisting of 918 observations.</p>
<p>Source: https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction</p>
</section>
<section id="data-dictionary" class="level2">
<h2 class="anchored" data-anchor-id="data-dictionary">Data Dictionary</h2>
<p>Age, RestingBP, Cholesterol, MaxHR, and Oldpeak are continuous variables. Sex, ChestPainType, FastingBS, RestingECG, ExerciseAngina, ST_Slope, and HeartDisease are categorical variables.<br>
Age: The age of the patient in years.<br>
Sex: The gender of the patient, identified as Male (M) or Female (F).<br>
ChestPainType: The type of chest pain experienced by the patient, classified as Typical Angina (TA), Atypical Angina (ATA), Non-Anginal Pain (NAP), or Asymptomatic (ASY).<br>
RestingBP: The resting blood pressure of the patient in mm Hg.<br>
Cholesterol: The level of serum cholesterol in mm/dL.<br>
FastingBS: The level of fasting blood sugar, indicated as 1 if FastingBS &gt; 120 mg/dL and 0 otherwise.<br>
RestingECG: The results of the patient’s resting electrocardiogram, classified as Normal, having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of &gt; 0.05 mV), or showing probable or definite left ventricular hypertrophy by Estes’ criteria (LVH).<br>
MaxHR: The maximum heart rate achieved by the patient, measured in beats per minute (bpm) and ranging from 60 to 202.<br>
ExerciseAngina: Whether the patient experienced exercise-induced angina, identified as Yes (Y) or No (N).<br>
Oldpeak: The degree of ST depression induced by exercise relative to rest, measured in depression.<br>
ST_Slope: The slope of the peak exercise ST segment, classified as Up (upsloping), Flat (flat), or Down (downsloping).<br>
HeartDisease: The output class indicating the presence (1) or absence (0) of heart disease.</p>
<div class="cell" data-messages="false">

</div>
<p>Source: https://www.kaggle.com/datasets/johnsmith88/heart-disease-dataset</p>
</section>
<section id="eda" class="level2">
<h2 class="anchored" data-anchor-id="eda">EDA</h2>
<p>As visualized in Figure 1, we found that 173 out of the 919 observations had a serum cholesterol level of 0 mm/dl. Since this is physiologically impossible, we decided to drop these observations.</p>
<p>We decide to use complete case analysis because it is relatively easy to implement, and it can reduce bias in the estimates of the variable of interest when the missing data are missing completely at random or missing at random. Although a complete case analysis in this case would lead to an approximately 20% sample loss, we believe that it is better than imputation because our current knowledge does not allow for accurate prediction of cholesterol levels of these observations.</p>
<div class="cell">

</div>
<p>As shown in Figure 2, the distribution of CVD appears to be relatively even between patients with/without the disease, suggesting that there is sufficient data available for both categories of the response variable to perform further statistical analysis and develop a predictive model.</p>
<p>Previous research has identified age, resting blood pressure, serum cholesterol, the presence of exercise-induced angina, and maximum heart rate as indicators of the presence of heart disease (Hajar, 2017). In addition, we suppose that sex should be an important predictor of CVDs because men are at a higher risk of developing CVDs than women (Maas, 2010). Thus, we will examine these predictors in our EDA, but still consider all of the remaining variables in when constructing our own model in the later sections.</p>
<p>As shown in Figure 3, patients with CVD clearly have a higher median age. Due to this difference, we will consider age as one of our predictor variables.</p>
<p>As shown in Figure 4, out of the patients in our datset, There is a nearly even split between men who do/do not have a CVD; about 45% of the men do not have a CVD, while about 55% of them do. However, females are much more likely to not have CVD (80% of them do not). Due to this apparent sex difference, we will consider including sex as a predictor variable as well.</p>
<p>Figure 5 shows that on average, patients diagnosed with CVD have higher resting blood pressure, which is consistent with the aforementioned literature findings.</p>
<p>Figure 6 shows that over 80% of patients with exercise-induced angina have CVD, whereas only around 25% of patients without exercise-induced angina have CVD. Therefore, exercise-induced angina might be an important predictor for CVDs as well.</p>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<p>We use a logistic regression model because we are trying to predict the log-odds of getting a CVD, a binary response variable. We plan to start with an all subset selection method with the 11 predictors in the dataset. An all subset selection takes all possible combinations of variables and predicts combination of variables leads to the “best” result. The results are evaluated based on Mallow’s Cp values. If adding new parameters doesn’t meaningfully decrease squared errors, the overall Cp score will be higher, hence the model with the lowest Cp score through an all subset selection will be chosen as the “best” model.</p>
</section>
<section id="all-subset-selection" class="level2">
<h2 class="anchored" data-anchor-id="all-subset-selection">All subset selection</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 255.73724 142.24583  93.94848  78.45767  42.99584  33.63583  23.26726
 [8]  17.63977  11.64749  10.81918  10.67854  10.93762  12.19263  14.09560
[15]  16.00000</code></pre>
</div>
</div>
<p>As shown in the table above, the model with the lowest Cp score is model 11. Model 11 includes 8 predictors: Age, Sex, ChestPainType, RestingBP, FastingBS, ExerciseAngina, Oldpeak, and ST_slope.</p>
<p>To validate our predictor selection approach, we performed stepwise selection in both directions on the dataset, yielding the same 8 predictors as the all subset selection method. These 8 predictors were deemed meaningful and subsequently used to fit a logistic model, which we will call Model 1, given the binary outcome of interest.</p>
</section>
<section id="model-attempts" class="level2">
<h2 class="anchored" data-anchor-id="model-attempts">Model attempts</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-4.9502150</td>
<td style="text-align: right;">1.2597480</td>
<td style="text-align: right;">-3.929528</td>
<td style="text-align: right;">0.0000851</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">0.0320180</td>
<td style="text-align: right;">0.0135006</td>
<td style="text-align: right;">2.371599</td>
<td style="text-align: right;">0.0177113</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SexM</td>
<td style="text-align: right;">1.7941249</td>
<td style="text-align: right;">0.3073380</td>
<td style="text-align: right;">5.837627</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">RestingBP</td>
<td style="text-align: right;">0.0124850</td>
<td style="text-align: right;">0.0072187</td>
<td style="text-align: right;">1.729548</td>
<td style="text-align: right;">0.0837111</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FastingBS</td>
<td style="text-align: right;">0.3225325</td>
<td style="text-align: right;">0.3260654</td>
<td style="text-align: right;">0.989165</td>
<td style="text-align: right;">0.3225824</td>
</tr>
<tr class="even">
<td style="text-align: left;">ChestPainTypeATA</td>
<td style="text-align: right;">-1.7002181</td>
<td style="text-align: right;">0.3492558</td>
<td style="text-align: right;">-4.868117</td>
<td style="text-align: right;">0.0000011</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ChestPainTypeNAP</td>
<td style="text-align: right;">-1.5968666</td>
<td style="text-align: right;">0.2964066</td>
<td style="text-align: right;">-5.387420</td>
<td style="text-align: right;">0.0000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">ChestPainTypeTA</td>
<td style="text-align: right;">-1.6370724</td>
<td style="text-align: right;">0.4715080</td>
<td style="text-align: right;">-3.471993</td>
<td style="text-align: right;">0.0005166</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ExerciseAnginaY</td>
<td style="text-align: right;">0.8882308</td>
<td style="text-align: right;">0.2624020</td>
<td style="text-align: right;">3.385001</td>
<td style="text-align: right;">0.0007118</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oldpeak</td>
<td style="text-align: right;">0.4124948</td>
<td style="text-align: right;">0.1398666</td>
<td style="text-align: right;">2.949201</td>
<td style="text-align: right;">0.0031860</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ST_SlopeFlat</td>
<td style="text-align: right;">1.2980847</td>
<td style="text-align: right;">0.5165720</td>
<td style="text-align: right;">2.512883</td>
<td style="text-align: right;">0.0119749</td>
</tr>
<tr class="even">
<td style="text-align: left;">ST_SlopeUp</td>
<td style="text-align: right;">-1.2244713</td>
<td style="text-align: right;">0.5592877</td>
<td style="text-align: right;">-2.189341</td>
<td style="text-align: right;">0.0285721</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Using a <span class="math inline">\(\alpha = 0.05\)</span> significance level, the p-values of RestingBP and FastingBS are respectively 0.084 and 0.32, which is larger than 0.05, suggesting the these 2 predictors might not be statistically significant. Hence, we considered a second logistic model with the 6 predictors left.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-3.6008458</td>
<td style="text-align: right;">0.9467300</td>
<td style="text-align: right;">-3.803456</td>
<td style="text-align: right;">0.0001427</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">0.0389149</td>
<td style="text-align: right;">0.0131564</td>
<td style="text-align: right;">2.957871</td>
<td style="text-align: right;">0.0030977</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SexM</td>
<td style="text-align: right;">1.7915558</td>
<td style="text-align: right;">0.2995667</td>
<td style="text-align: right;">5.980491</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">ChestPainTypeATA</td>
<td style="text-align: right;">-1.6554956</td>
<td style="text-align: right;">0.3444960</td>
<td style="text-align: right;">-4.805558</td>
<td style="text-align: right;">0.0000015</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ChestPainTypeNAP</td>
<td style="text-align: right;">-1.5793224</td>
<td style="text-align: right;">0.2958402</td>
<td style="text-align: right;">-5.338430</td>
<td style="text-align: right;">0.0000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">ChestPainTypeTA</td>
<td style="text-align: right;">-1.5108657</td>
<td style="text-align: right;">0.4633904</td>
<td style="text-align: right;">-3.260460</td>
<td style="text-align: right;">0.0011123</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ExerciseAnginaY</td>
<td style="text-align: right;">0.9354101</td>
<td style="text-align: right;">0.2605893</td>
<td style="text-align: right;">3.589595</td>
<td style="text-align: right;">0.0003312</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oldpeak</td>
<td style="text-align: right;">0.4214819</td>
<td style="text-align: right;">0.1378234</td>
<td style="text-align: right;">3.058129</td>
<td style="text-align: right;">0.0022272</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ST_SlopeFlat</td>
<td style="text-align: right;">1.2392333</td>
<td style="text-align: right;">0.5104693</td>
<td style="text-align: right;">2.427635</td>
<td style="text-align: right;">0.0151976</td>
</tr>
<tr class="even">
<td style="text-align: left;">ST_SlopeUp</td>
<td style="text-align: right;">-1.2746532</td>
<td style="text-align: right;">0.5515375</td>
<td style="text-align: right;">-2.311091</td>
<td style="text-align: right;">0.0208278</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>#exercise angina Exercise-induced angina refers to chest pain or discomfort that occurs during physical activity, such as exercise, and is usually a result of reduced blood flow to the heart. It can be a symptom of underlying heart disease, such as coronary artery disease, which can be caused by the buildup of plaque in the arteries that supply the heart with blood. Therefore, the presence or absence of exercise-induced angina can be a useful diagnostic tool in identifying individuals at risk for or already suffering from heart disease.</p>
<p>#old peak The variable “Oldpeak” refers to the ST segment depression induced by exercise relative to rest. It is a numeric variable that measures the difference in the ST segment of an electrocardiogram (ECG) before and after exercise. A positive value of Oldpeak indicates that the ST segment is depressed during exercise compared to at rest, which can be a sign of ischemia (insufficient blood flow) to the heart. The greater the magnitude of the depression, the more severe the ischemia. Therefore, Oldpeak is a useful predictor of the likelihood of heart disease and can be used in models to predict the risk of heart failure.</p>
<p>#st slope The variable “ST_Slope” makes sense to include, as the ST segment exercise test, is one of the most widely used tests to screen for CVDs. Either depression (horizontal or downsloping) in the slope often suggests presence of CAD and warrants further management (Lim, 2016).</p>
<p>Finally, we fitted a logistic model with all predictors included in order to provide a baseline of comparing the models.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-5.4373046</td>
<td style="text-align: right;">1.7625169</td>
<td style="text-align: right;">-3.0849659</td>
<td style="text-align: right;">0.0020358</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">0.0313784</td>
<td style="text-align: right;">0.0148105</td>
<td style="text-align: right;">2.1186575</td>
<td style="text-align: right;">0.0341194</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SexM</td>
<td style="text-align: right;">1.8655490</td>
<td style="text-align: right;">0.3134065</td>
<td style="text-align: right;">5.9524904</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">ChestPainTypeATA</td>
<td style="text-align: right;">-1.6731804</td>
<td style="text-align: right;">0.3544226</td>
<td style="text-align: right;">-4.7208630</td>
<td style="text-align: right;">0.0000023</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ChestPainTypeNAP</td>
<td style="text-align: right;">-1.5730121</td>
<td style="text-align: right;">0.3029404</td>
<td style="text-align: right;">-5.1924797</td>
<td style="text-align: right;">0.0000002</td>
</tr>
<tr class="even">
<td style="text-align: left;">ChestPainTypeTA</td>
<td style="text-align: right;">-1.6332529</td>
<td style="text-align: right;">0.4838117</td>
<td style="text-align: right;">-3.3758029</td>
<td style="text-align: right;">0.0007360</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RestingBP</td>
<td style="text-align: right;">0.0117792</td>
<td style="text-align: right;">0.0072988</td>
<td style="text-align: right;">1.6138654</td>
<td style="text-align: right;">0.1065566</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cholesterol</td>
<td style="text-align: right;">0.0024955</td>
<td style="text-align: right;">0.0019773</td>
<td style="text-align: right;">1.2620586</td>
<td style="text-align: right;">0.2069277</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FastingBS</td>
<td style="text-align: right;">0.2923999</td>
<td style="text-align: right;">0.3311265</td>
<td style="text-align: right;">0.8830458</td>
<td style="text-align: right;">0.3772115</td>
</tr>
<tr class="even">
<td style="text-align: left;">RestingECGNormal</td>
<td style="text-align: right;">-0.2297888</td>
<td style="text-align: right;">0.2842091</td>
<td style="text-align: right;">-0.8085204</td>
<td style="text-align: right;">0.4187911</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RestingECGST</td>
<td style="text-align: right;">-0.1746017</td>
<td style="text-align: right;">0.3941671</td>
<td style="text-align: right;">-0.4429637</td>
<td style="text-align: right;">0.6577920</td>
</tr>
<tr class="even">
<td style="text-align: left;">MaxHR</td>
<td style="text-align: right;">0.0005807</td>
<td style="text-align: right;">0.0057810</td>
<td style="text-align: right;">0.1004456</td>
<td style="text-align: right;">0.9199906</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ExerciseAnginaY</td>
<td style="text-align: right;">0.9073515</td>
<td style="text-align: right;">0.2671360</td>
<td style="text-align: right;">3.3965895</td>
<td style="text-align: right;">0.0006823</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oldpeak</td>
<td style="text-align: right;">0.4108355</td>
<td style="text-align: right;">0.1406671</td>
<td style="text-align: right;">2.9206235</td>
<td style="text-align: right;">0.0034933</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ST_SlopeFlat</td>
<td style="text-align: right;">1.3038217</td>
<td style="text-align: right;">0.5197574</td>
<td style="text-align: right;">2.5085195</td>
<td style="text-align: right;">0.0121238</td>
</tr>
<tr class="even">
<td style="text-align: left;">ST_SlopeUp</td>
<td style="text-align: right;">-1.2100372</td>
<td style="text-align: right;">0.5655279</td>
<td style="text-align: right;">-2.1396597</td>
<td style="text-align: right;">0.0323823</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">

<table class="kable_wrapper">
<tbody>
<tr>
<td>
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">roc_auc</td>
<td style="text-align: left;">binary</td>
<td style="text-align: right;">0.9344641</td>
</tr>
</tbody>
</table>
</td>
<td>
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">roc_auc</td>
<td style="text-align: left;">binary</td>
<td style="text-align: right;">0.9329264</td>
</tr>
</tbody>
</table>
</td>
<td>
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">roc_auc</td>
<td style="text-align: left;">binary</td>
<td style="text-align: right;">0.9349323</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>

</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="final-project_files/figure-html/attempting%20to%20color%20and%20overlap%20the%203%20roc%20curves-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">Resid. Df</th>
<th style="text-align: right;">Resid. Dev</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Deviance</th>
<th style="text-align: right;">Pr(&gt;Chi)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">736</td>
<td style="text-align: right;">490.7443</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">734</td>
<td style="text-align: right;">486.1341</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4.610217</td>
<td style="text-align: right;">0.099748</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">Resid. Df</th>
<th style="text-align: right;">Resid. Dev</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Deviance</th>
<th style="text-align: right;">Pr(&gt;Chi)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">736</td>
<td style="text-align: right;">490.7443</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">730</td>
<td style="text-align: right;">483.5804</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7.163848</td>
<td style="text-align: right;">0.3059602</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The p-values are 0.10 and 0.306 (&gt;0.05 significance level) when comparing model 2 to model 1, and model 2 to model 3. This indicate that there is not enough evidence to reject the null hypothesis that all of the slopes corresponding to the eliminated terms (Cholesterol, RestingECG, MaxHR, RestingBP, and FastingBS) are zero. Therefore, there is not enough evidence to conclude that the model with all predictors is significantly better than the model we created through all subset selection. We would prefer to use the simpler Model 2 (that we came up with through all subset selection and p-value emliniation) over the more complex Model 3 (which includes all of the predictors), as it has fewer variables and possibly has clearer interpretations.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">Resid. Df</th>
<th style="text-align: right;">Resid. Dev</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Deviance</th>
<th style="text-align: right;">Pr(&gt;Chi)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">734</td>
<td style="text-align: right;">486.1341</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">736</td>
<td style="text-align: right;">490.7443</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">-4.610217</td>
<td style="text-align: right;">0.099748</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>explain this!! mention that the cut off for the predictions is 0.5!</p>
</section>
<section id="assumptions" class="level2">
<h2 class="anchored" data-anchor-id="assumptions">Assumptions</h2>
<p>The two assumptions that are important in logistic regression are independence and linearity.</p>
<p>Independence: There might be violations of independence. The dataset is a combination of five datasets from clinics at Cleveland, Hungarian, Switzerland, Long Beach VA, and the Stalog (Heart) Dataset. If, for example, the different institutions had different in measuring Max heart rate, or the Oldpeak that would lead to systematic differences, then knowing one observation might yield information on another observation. However, since the exact data collecting mechanism is unknown, and we are not knowledgable information to make deductions and act upon violations of independence, we assume that independence is not violated.</p>
<p>Linearity: The 5 continuous variables that are involved in all models are Age, RestingBP, Cholesterol, MaxHR, and Oldpeak. As shown in all five plots below, the dots are randomly scattered across the empirical logits plots. Therefore, the linearity assumption is satisfied for the model. plots are figure 6</p>
<p>#cholesterol Research suggests that low-density lipoprotein cholesterol (LDL-C, the “bad” cholesterol) is not the best predictor of risk for a major coronary event in people who are generally healthy otherwise.</p>
<p>#resting ecg The variable “RestingECG” may not be the best predictor of heart disease because it is only measuring the resting electrocardiogram results. Many people with heart disease may have a normal resting electrocardiogram, while others without heart disease may show abnormalities in their resting electrocardiogram. In contrast, other variables in the dataset, such as “ExerciseAngina” and “Oldpeak”, are more directly related to the physiological response to exercise, which can be a stronger predictor of heart disease. Additionally, “RestingECG” only provides information about the electrical activity of the heart at rest, while “ExerciseAngina” provides information about the heart’s response to physical stress, which can be a more sensitive indicator of heart disease.</p>
<p>#max hr Max heart rate is not the best predictor of heart disease because it is highly confounded by age. As we age, our maximum heart rate decreases, so older individuals will have lower maximum heart rates even if they are healthy. Furthermore, medications for CVDs include beta blockers, which naturally slows down a person’s heart rate.</p>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<p>#Equation log(odds) = -3.60 + 0.039 (Age) + 1.792 (Sex Male) - 1.656 (Atypical Anginal Chest Pain) - 1.579 (NonAnginal Chest Pain) -1.511 (Typical Anginal Chest Pain) + 0.935(Exercise Angina) + 0.421(OldPeak) + 1.239(St_SlopeFlat) -1.275(ST_SlopeUp)</p>
<p>After evaluating and comparing the model performances using the ROC curve, the AUC metric, and an F-test (all three models are nested), we see that all three models achieved very similar performance in terms of AUC score (0.934 for model 1, 0.933 for model 2, and 0.935 for model 3). We selected model 2 as our final model, although it seems to have the lowest AUC score among all three models, because our F-tests show that model 2 is not significantly different from model 1 and model 3. This suggests that there is not sufficient evidence indicating that it is helpful to additionally include the other five predictors Cholesterol, RestingECG, MaxHR, RestingBP, and FastingBS in the model.</p>
<p>The intercept for our model represents a newborn female with no chest pain, no exercise-induced angina, no ST depression (0 degrees) on their ECG upon exercise that remains flat throughout exercise. The intercept value corresponds to log-odds of having a CVD vs.&nbsp;not having a CVD being 0.027 (<span class="math inline">\(e^{-3.6}\)</span>) in this population. Consistent with existing scientific literature, we see in our chosen model that as people get older, their log-odds of developing a CVD increases; specifically, their log-odds is expected to increase by <span class="math inline">\(e^{0.039=1.04}\)</span> with every passing year. We found that sex is positively correlated with the log-odds of developing a CVD, in that a male’s likelihood of having a CVD is expected to be <span class="math inline">\(e^{1.792} = 6.00\)</span> times that of a female, holding all else constant. As mentioned before, this is consistent with existing scientific literature. We also found that if a patient has exercise angina, their likelihood of having a CVD is <span class="math inline">\(e^{0.935}=2.55\)</span> times higher than that of a patient who doesn’t have exercise angina, when holding all other variables constant. This makes sense because exercise angina has to do with discomfort when heart muscle receives insufficient blood and oxygen during physical activity, which is mostly due to narrowing of arteries and can lead to CVDs and heart failure. With every degree increase in the depression of the ST segment slope on a patient’s ECG during exercise, their log-odds of developing a CVD is expected to increase by <span class="math inline">\(e^{0.421}=1.52\)</span> times. In a similar train of logic, our model also shows that when compared to a decreasing ST slope during exercise, having an flat ST slope is expected to increase a patient’s log-odds of developing a CVD by <span class="math inline">\(e^{1.239}=3.45\)</span> and having an upwards ST slope is expected to decrease their log-odds by <span class="math inline">\(e^{-1.275}=0.28\)</span>.</p>
<p>An unexpected discovery from our model is that people who are asymptomatic for chest pain are predicted to have the highest logodds of developing CVD, while controlling for all other variables. This might be explained through two layers of analysis. First, this dataset is not collected randomly from any population, but rather from people who visit the clinics and are probably suspected to have heart diseases. Hence, there is some sort of self-selection to get these variables documented when a participant does not experience chest pain yet is suspected to have heart disease. Second, how long the patients have been diagnosed with CVD is unknown, therefore some patients might have actively engaged in treatment processes and no longer experience chest pain, while still under the diagnosis of CVD.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>In this section you’ll include a summary of what you have learned about your research question along with statistical arguments supporting your conclusions. In addition, discuss the limitations of your analysis and provide suggestions on ways the analysis could be improved. Any potential issues pertaining to the reliability and validity of your data and appropriateness of the statistical analysis should also be discussed here. Lastly, this section will include ideas for future work.</p>
<p>#Summary Our model identified the main predictors for cardiovascular disease in this dataset and quantified their impact on the likelihood of having the disease. We found that traditional factors such as [cholesterol and blood pressure] lose their predictive power when richer data is available, such as [fluoroscopy and electrocardiogram results, presence of other diseases, chest pain, and exercise tests].</p>
<p>#What we’ve learned about our research question - newer research is emerging, some of the metrics that we commonly think of as highly predictive actually aren’t that good (can use cholesterol as an example) –&gt; After identifying 172 data points with zero cholesterol levels, which is biologically implausible, we opted to exclude them from our study. Nonetheless, we noticed that these eliminated observations had a greater probability of presenting CVD than the average in the complete dataset. Therefore, the exclusion of these data points may have decreased the reliability of our analysis by reducing the sample size from 918 to 746, which could have introduced bias into our results. The validity of our study might be compromised due to the exclusion of this relevant information.</p>
<p>#Limitations and Improvements Our analysis is limited due to the non-representativeness of the dataset, which only includes individuals admitted to hospitals for heart disease-related conditions. As a result, our findings cannot be generalized to the broader population. To address this limitation, future studies should aim to expand the sample size and include a more diverse population to enhance the generalizability of the results. Additionally, we suggest that future research should focus on developing predictive models for heart disease in the general population by collecting data from the general population, as early detection can facilitate lifestyle changes or prompt timely treatment.</p>
<p>#Limitations of our analysis - better ways we couldve done it? –&gt; adding interaction terms Age and Sex: Studies have shown that the relationship between age and heart disease risk may differ by sex, with women generally having a later onset of heart disease compared to men.</p>
<p>Chest Pain Type and Sex: Some studies suggest that there may be differences in the way men and women experience chest pain during a heart attack, which could potentially impact the predictive power of chest pain type in a heart disease model.</p>
<p>Exercise Angina and Oldpeak: Exercise-induced angina and ST depression during exercise are both markers of ischemia (reduced blood flow to the heart), and may therefore be related to each other in predicting heart disease risk.</p>
<p>Oldpeak and ST Slope: The shape of the ST segment during exercise can be indicative of different types of ischemia, and may therefore have a complex relationship with the severity of heart disease risk as measured by the degree of ST depression (Oldpeak).</p>
<p>#talk about how the variables were already narrowed down, making it hard for us It is important to emphasize that the list of 11 variables under consideration in this study has been narrowed down by researchers from a list of 76, involving several previous research studies to confirm this cut. As a result, further reduction of these variables from a model including all 11 variables could be somewhat challenging.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 746  12</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.9066</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.9027</code></pre>
</div>
</div>
<p>we also attempted a simple hold-out method, in which 80% of the data was used as a training set and 20%</p>
<p>References: Centers for Disease Control and Prevention, National Center for Health Statistics. About Multiple Cause of Death, 1999–2020. CDC WONDER Online Database website. Atlanta, GA: Centers for Disease Control and Prevention; 2022. Accessed May 1, 2023.</p>
<p>Damen, J. A., Hooft, L., Schuit, E., Debray, T. P., Collins, G. S., Tzoulaki, I., Lassale, C. M., Siontis, G. C., Chiocchia, V., Roberts, C., Schlüssel, M. M., Gerry, S., Black, J. A., Heus, P., van der Schouw, Y. T., Peelen, L. M., &amp; Moons, K. G. (2016). Prediction models for cardiovascular disease risk in the general population: systematic review. BMJ (Clinical research ed.), 353, i2416. https://doi.org/10.1136/bmj.i2416</p>
<p>Downs, J. R., Clearfield, M., Weis, S., Whitney, E., Shapiro, D. R., Beere, P. A., Langendorfer, A., Stein, E. A., Kruyer, W., &amp; Gotto, A. M., Jr (1998). Primary prevention of acute coronary events with lovastatin in men and women with average cholesterol levels: results of AFCAPS/TexCAPS. Air Force/Texas Coronary Atherosclerosis Prevention Study. JAMA, 279(20), 1615–1622. https://doi.org/10.1001/jama.279.20.1615</p>
<p>Fedesoriano. (September 2021). Heart Failure Prediction Dataset. Retrieved [May 2, 2023] from https://www.kaggle.com/fedesoriano/heart-failure-prediction.</p>
<p>Lim, Y. C., Teo, S. G., &amp; Poh, K. K. (2016). ST-segment changes with exercise stress. Singapore medical journal, 57(7), 347–353. https://doi.org/10.11622/smedj.2016116</p>
<p>Maas, A. H., &amp; Appelman, Y. E. (2010). Gender differences in coronary heart disease. Netherlands heart journal : monthly journal of the Netherlands Society of Cardiology and the Netherlands Heart Foundation, 18(12), 598–602. https://doi.org/10.1007/s12471-010-0841-y</p>
<p>Velagaleti, R. S., &amp; Vasan, R. S. (2007). Heart failure in the twenty-first century: is it a coronary artery disease or hypertension problem?. Cardiology clinics, 25(4), 487–v. https://doi.org/10.1016/j.ccl.2007.08.010</p>
<section id="appendix" class="level3">
<h3 class="anchored" data-anchor-id="appendix">Appendix</h3>
<p>#Figure 1: Missing Data</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="final-project_files/figure-html/figure%201%20missing%20data-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<p>#Figure 2: Distribution of Patients With/Without CVDs</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="final-project_files/figure-html/cvd-distribution%20figure%202-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<p>#Figure 3: Box Plot for Age</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="final-project_files/figure-html/figure%203%20box%20plot%20for%20age-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<p>#Figure 4: Proportion Plot for Sex</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="final-project_files/figure-html/proportion%20plot%20for%20sex%20figure%204-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<p>#Figure 5: Box Plot for Resting Blood Pressure</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="final-project_files/figure-html/figure%205%20box%20plot%20for%20resting%20blood%20pressure-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<p>#Figure 6: Proportion Plot for Exercise Angina</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="final-project_files/figure-html/figure%206%20proportion%20plot%20for%20exercise%20angina-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<p>#Figure 7: Linearity Assumption Diagnostic Plots for Continuous Variables</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="final-project_files/figure-html/figure%207%20assumptions-1.png" class="img-fluid" width="576"></p>
</div>
<div class="cell-output-display">
<p><img src="final-project_files/figure-html/figure%207%20assumptions-2.png" class="img-fluid" width="576"></p>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>